(function(){
'use strict';
const $=id=>document.getElementById(id);
if(!$('academy'))return;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const L=(id,cat,title,level,time,goal,theory,steps,measure,mistakes,q,opts,ans,why)=>({id,cat,title,level,time,goal,theory,steps,measure,mistakes,q,opts,ans,why});
const lessons=[
L('b1','Podstawy','Bezpieczna kolejność diagnostyki','Podstawowy','15 min','Nauczyć się diagnozować bez wymieniania części na próbę.','Prawidłowa diagnoza zaczyna się od potwierdzenia objawu, wywiadu i oględzin. Kod DTC jest wskazówką, a nie wyrokiem na część.', ['Potwierdź objaw i warunki jego występowania.','Zapisz wszystkie DTC oraz freeze frame przed kasowaniem.','Sprawdź akumulator, bezpieczniki, złącza, masy i ślady wcześniejszych napraw.','Wybierz test, który rozdziela dwie najbardziej prawdopodobne przyczyny.'], 'Zapisuj wynik, warunki i punkt pomiarowy. Po każdej naprawie wykonaj test potwierdzający.','Kasowanie błędów przed zapisem danych; zakup części tylko na podstawie kodu; pomijanie oględzin.','Co oznacza kod DTC?',['Pewną informację, którą część wymienić','Wskazanie obwodu lub warunku wymagającego sprawdzenia','Zawsze uszkodzony sterownik'],1,'DTC opisuje wykryty problem obwodu lub warunku pracy. Przyczyną może być element, przewód, zasilanie, masa albo inny układ.'),
L('b2','Podstawy','Multimetr w instalacji samochodowej','Podstawowy','20 min','Poprawnie mierzyć napięcie, rezystancję i ciągłość.','Napięcie mierzymy równolegle na zasilonym obwodzie. Rezystancję i ciągłość mierzymy bez napięcia. Sygnał brzęczyka nie potwierdza jakości przewodu pod obciążeniem.', ['Sprawdź stan przewodów i gniazd miernika.','Dla instalacji 12 V wybierz V DC i właściwy zakres.','Czarną sondę połącz z pewną masą, czerwoną z badanym punktem.','Rezystancję mierz po odłączeniu zasilania badanego obwodu.'], 'Akumulator spoczynkowo zwykle około 12,6 V po pełnym naładowaniu; wartości oceniaj wraz z temperaturą i stanem akumulatora.','Pomiar amperomierzem równolegle do akumulatora; pomiar Ω na zasilonym układzie; przebijanie izolacji bez zabezpieczenia.','Jak podłączamy woltomierz?',['Szeregowo','Równolegle','Zamiast bezpiecznika zawsze'],1,'Woltomierz porównuje potencjał dwóch punktów, dlatego podłącza się go równolegle.'),
L('b3','Podstawy','Spadek napięcia pod obciążeniem','Podstawowy','20 min','Wykrywać słabe przewody, złącza i masy.','Przewód może mieć przejście bez obciążenia, lecz pod dużym prądem powodować znaczny spadek. Test spadku wykonuje się podczas pracy obwodu.', ['Uruchom odbiornik lub rozrusznik.','Zmierz napięcie między początkiem i końcem przewodu dodatniego.','Powtórz pomiar po stronie masowej.','Jeśli spadek jest nadmierny, dziel odcinek na krótsze fragmenty.'], 'Dla obwodów dużego prądu oczekujemy bardzo małych spadków; dokładny limit potwierdź dokumentacją producenta.','Test ciągłości jako jedyny test przewodu; brak obciążenia; pomiar względem przypadkowej masy.','Kiedy test spadku napięcia jest miarodajny?',['Gdy obwód jest obciążony','Tylko po wyjęciu bezpiecznika','Wyłącznie przy odłączonym akumulatorze'],0,'Spadek ujawnia opór połączenia dopiero wtedy, gdy płynie prąd.'),
L('b4','Podstawy','Czytanie schematu elektrycznego','Podstawowy','25 min','Śledzić zasilanie, masę i sygnał od źródła do odbiornika.','Schemat pokazuje zależności elektryczne, nie zawsze fizyczne położenie elementów. Zacznij od numerów pinów, złączy, bezpieczników i punktów masowych.', ['Zaznacz źródło zasilania i warunki włączenia.','Znajdź bezpiecznik, przekaźnik, odbiornik i masę.','Wypisz złącza i numery pinów na drodze obwodu.','Wybierz punkty pomiarowe dzielące obwód na połowy.'], 'Na każdym punkcie określ oczekiwane napięcie lub przebieg przed pomiarem.','Mylenie widoku złącza od strony przewodów i pinów; ignorowanie warunków aktywacji; pomiar nie tego wariantu auta.','Co najpierw ustalasz na schemacie?',['Kolor obudowy sterownika','Źródło zasilania, odbiornik i masę','Cenę części'],1,'Te trzy elementy wyznaczają podstawową drogę prądu i pozwalają zaplanować pomiary.'),
L('b5','Podstawy','Bezpiecznik i przekaźnik','Podstawowy','20 min','Odróżniać skutek od przyczyny przepalenia bezpiecznika.','Bezpiecznik chroni przewód przed nadmiernym prądem. Przekaźnik pozwala małym sygnałem sterować większym obciążeniem.', ['Sprawdź bezpiecznik wizualnie i miernikiem po obu stronach.','Przy przepaleniu szukaj zwarcia, nie zakładaj większego bezpiecznika.','Ustal piny cewki i styków przekaźnika ze schematu.','Sprawdź zasilanie cewki, sterowanie, masę oraz spadek na stykach.'], 'Pod obciążeniem napięcie po obu stronach sprawnego bezpiecznika powinno być praktycznie takie samo.','Wkładanie większego bezpiecznika; zwieranie gniazda drutem; zamiana przekaźnika bez sprawdzenia pinów.','Co zrobić po ponownym przepaleniu bezpiecznika?',['Włożyć większy','Szukać zwarcia lub przeciążenia','Zewrzeć styki na stałe'],1,'Ponowne przepalenie oznacza, że przyczyna nadmiernego prądu nadal istnieje.'),
L('b6','Podstawy','Dokumentowanie diagnozy','Podstawowy','12 min','Tworzyć powtarzalny zapis pomiarów i wniosków.','Dobry zapis zawiera dane auta, warunki, DTC, wartości oczekiwane, wyniki oraz decyzję. Chroni przed powtarzaniem testów i zgadywaniem.', ['Zapisz VIN, silnik, przebieg i historię napraw.','Zapisz objaw własnymi słowami klienta i wynik potwierdzenia.','Do każdego pomiaru dopisz jednostkę, punkt i warunki.','Po naprawie zapisz test końcowy i rezultat jazdy próbnej.'], 'Zrzuty freeze frame i wykresy live data warto zachować przed kasowaniem błędów.','Brak jednostek; zdjęcie bez opisu punktu; zapis tylko wyniku „OK”; brak testu po naprawie.','Co musi towarzyszyć wartości pomiarowej?',['Tylko data','Jednostka, punkt i warunki','Numer zamówionej części'],1,'Bez tych informacji wynik może być niemożliwy do poprawnej interpretacji.'),
L('e1','Elektryka','Akumulator i test rozruchu','Podstawowy','25 min','Ocenić stan zasilania przed dalszą diagnostyką.','Niskie napięcie podczas rozruchu może wywołać liczne fałszywe DTC i utratę komunikacji. Sam pomiar spoczynkowy nie zastępuje testu pod obciążeniem.', ['Wykonaj oględziny, sprawdź klemy i stan naładowania.','Zmierz napięcie spoczynkowe po ustabilizowaniu.','Zarejestruj minimum napięcia podczas rozruchu.','Zmierz spadki na przewodzie dodatnim i masowym rozrusznika.'], 'Interpretuj wyniki według typu akumulatora, temperatury i specyfikacji producenta auta.','Diagnoza sterowników przy rozładowanym akumulatorze; test tylko bez obciążenia; ignorowanie klem i masy.','Dlaczego słaby akumulator tworzy wiele DTC?',['Zawsze uszkadza ECU','Powoduje spadki napięcia i resetowanie modułów','Zmienia numer VIN'],1,'Moduły mogą przestać komunikować się lub rejestrować błędy zasilania podczas spadku.'),
L('e2','Elektryka','Układ ładowania i alternator','Średni','25 min','Rozdzielić problem alternatora, przewodów i sterowania.','Nowoczesny alternator może być sterowany przez ECU/LIN i nie zawsze utrzymuje stałe 14,4 V. Oceniaj napięcie, prąd, tętnienia i sygnał sterujący.', ['Sprawdź pasek, połączenia B+ i masę silnika.','Zmierz napięcie akumulatora przed i po uruchomieniu.','Włącz odbiorniki i obserwuj odpowiedź układu.','Zmierz spadek na B+ i masie oraz tętnienia AC.'], 'Porównaj zadane i rzeczywiste ładowanie w live data, jeśli system jest inteligentny.','Skazanie alternatora tylko po jednym napięciu; pominięcie B+ i masy; odłączanie klemy na pracującym silniku.','Czy wolno odłączać akumulator podczas pracy silnika?',['Tak, to najlepszy test','Nie, grozi przepięciem i uszkodzeniem elektroniki','Tylko w dieslu'],1,'Odłączenie może spowodować niekontrolowane przepięcie i nie jest bezpiecznym testem.'),
L('e3','Elektryka','Rozrusznik i obwód dużego prądu','Średni','25 min','Ustalić, czy winny jest akumulator, przewody, sterowanie czy rozrusznik.','Wolne kręcenie wymaga równoczesnej oceny napięcia, prądu i spadków. Kliknięcie elektromagnesu nie potwierdza sprawności toru mocy.', ['Sprawdź napięcie akumulatora podczas próby.','Zmierz spadek od plusa akumulatora do zacisku rozrusznika.','Zmierz spadek między obudową rozrusznika a minusem akumulatora.','Sprawdź sygnał sterujący elektromagnesu oraz prąd rozruchu.'], 'Porównuj prędkość obrotową i pobór z danymi dla silnika oraz temperaturą.','Wymiana rozrusznika bez testu masy; długie próby przegrzewające przewody; zwarcie zacisków bez zabezpieczenia.','Duży spadek po stronie masowej wskazuje najpierw na:',['Przewód lub połączenie masowe','Czujnik temperatury','Sondę lambda'],0,'Napięcie ginie na oporze między rozrusznikiem a minusem akumulatora.'),
L('e4','Elektryka','Pobór prądu na postoju','Średni','30 min','Bezpiecznie znaleźć obwód rozładowujący akumulator.','Auto potrzebuje czasu na uśpienie modułów. Otwarcie drzwi lub wyjęcie bezpiecznika może obudzić sieć i zmienić wynik.', ['Naładuj i sprawdź akumulator.','Przygotuj zamki drzwi/klap tak, aby auto mogło zasnąć.','Podłącz amperomierz bez przerywania zasilania albo użyj cęgów DC.','Po uśpieniu lokalizuj gałąź pomiarem spadków na bezpiecznikach lub kontrolowanym odłączaniem.'], 'Dopuszczalny pobór zależy od auta i wyposażenia; potwierdź specyfikację i czas uśpienia.', 'Przekroczenie zakresu miernika; otwieranie auta w trakcie testu; ocena przed uśpieniem; wyrywanie bezpieczników bez planu.','Dlaczego czekamy na uśpienie auta?',['Aby moduły zakończyły aktywność i pobór ustabilizował się','Aby schłodzić silnik','Aby skasować DTC'],0,'Dopiero po uśpieniu można ocenić rzeczywisty pobór postojowy.'),
L('e5','Elektryka','Zasilania i masy sterownika','Średni','25 min','Sprawdzić ECU/BCM przed podejrzeniem jego uszkodzenia.','Sterownik może mieć kilka stałych i zapłonowych zasilań oraz wiele mas. Wszystkie trzeba sprawdzić pod obciążeniem zgodnie ze schematem.', ['Odczytaj pinout właściwego numeru sterownika.','Sprawdź bezpieczniki z obu stron pod obciążeniem.','Zmierz każde zasilanie względem pewnej masy.','Wykonaj test spadku każdej masy podczas aktywności sterownika.'], 'Brak komunikacji często wynika z braku jednego zasilania, masy lub zakłócenia magistrali.','Wymiana ECU przed testem pinów; użycie próbówki na delikatnej linii; mylenie stałego plusa z plusem po zapłonie.','Co sprawdzić przed wymianą sterownika?',['Tylko kod DTC','Wszystkie zasilania, masy i komunikację','Kolor obudowy'],1,'Sterownik nie może pracować bez prawidłowych warunków zewnętrznych.'),
L('e6','Elektryka','Zwarcie i lokalizacja uszkodzonej gałęzi','Zaawansowany','30 min','Zawężać zwarcie bez uszkadzania wiązki.','Najpierw potwierdź, po której stronie bezpiecznika występuje zwarcie i jakie odbiorniki należą do gałęzi. Ograniczone zasilanie może pomóc, ale wymaga znajomości obwodu.', ['Odłącz akumulator i potwierdź zwarcie odpowiednim pomiarem.','Ze schematu wypisz wszystkie odgałęzienia i złącza.','Odłączaj gałęzie w logicznych punktach, obserwując zmianę.','Jeśli stosujesz ograniczone zasilanie, ustaw bezpieczne napięcie i limit prądu dla obwodu.'], 'Kamera termiczna lub kontrolowany spadek napięcia na przewodzie może wskazać miejsce przepływu prądu.', 'Podawanie 12 V na nieznaną linię 5 V; zastępowanie bezpiecznika drutem; rozcinanie wiązki bez schematu.','Pierwszy krok przy przepalającym się bezpieczniku to:',['Założyć większy','Ustalić odbiorniki i gałęzie chronione tym bezpiecznikiem','Wymienić BCM'],1,'Schemat i podział gałęzi pozwalają lokalizować zwarcie bez losowego odłączania.'),
L('c1','Komunikacja','Podstawy magistrali CAN','Średni','25 min','Rozumieć rolę CAN-H, CAN-L i terminacji.','CAN jest magistralą różnicową. Dwa rezystory terminujące po 120 Ω dają zwykle około 60 Ω między CAN-H i CAN-L przy wyłączonym zasilaniu, ale topologia auta może się różnić.', ['Wyłącz zasilanie zgodnie z procedurą i pozwól modułom zasnąć.','Zmierz rezystancję między CAN-H i CAN-L.','Sprawdź zwarcie każdej linii do plusa i masy.','Na zasilonym układzie oceń napięcia lub przebiegi oscyloskopem.'], 'Pomiar około 120 Ω może oznaczać brak jednej terminacji lub przerwę odcinka; 0 Ω sugeruje zwarcie między liniami.', 'Pomiar Ω na aktywnej magistrali; zwieranie linii próbówką; uznanie 60 Ω za regułę dla każdej sieci.','Typowa rezystancja dwóch terminatorów 120 Ω równolegle to:',['240 Ω','120 Ω','60 Ω'],2,'Dwa rezystory 120 Ω połączone równolegle dają 60 Ω.'),
L('c2','Komunikacja','Brak komunikacji z jednym modułem','Średni','25 min','Oddzielić usterkę modułu od zasilania i odcinka sieci.','Jeśli inne moduły komunikują się, sprawdź status badanego modułu w topologii, jego zasilania, masy i lokalne odgałęzienie CAN/LIN.', ['Wykonaj pełny autoscan i zapisz moduły obecne oraz nieobecne.','Sprawdź zasilania i masy brakującego modułu.','Sprawdź ciągłość lokalnych linii komunikacji zgodnie ze schematem.','Odłącz moduł tylko zgodnie z procedurą i obserwuj, czy sieć wraca.'], 'Kod U w innych modułach pomaga ustalić, kto utracił komunikację i kiedy.', 'Natychmiastowa wymiana modułu; kodowanie używanego modułu bez diagnozy; pominięcie wilgoci w złączu.','Inne moduły działają, jeden jest niewidoczny. Co najpierw?',['Zasilania, masy i jego odgałęzienie sieci','Wymiana akumulatora bez testu','Kasowanie wszystkich kodów'],0,'Brak zasilania lub masy jest częstszą i prostszą przyczyną niż awaria samego modułu.'),
L('c3','Komunikacja','LIN i sterowanie pojedynczym przewodem','Średni','20 min','Diagnozować podsystemy sterowane magistralą LIN.','LIN używa zwykle jednego przewodu sygnałowego i konfiguracji master–slave. Zwarcie jednego urządzenia może zablokować całą gałąź.', ['Ustal mastera, urządzenia slave i pin sygnału.','Sprawdź zasilanie i masę każdego urządzenia.','Oscyloskopem sprawdź obecność ramek na LIN.','Odłączaj urządzenia slave według schematu, aby znaleźć blokujące.'], 'Multimetr pokaże wartość uśrednioną; oscyloskop ujawni aktywność i jakość przebiegu.', 'Oczekiwanie rezystancji 60 Ω jak w CAN; podawanie plusa na LIN; pominięcie zasilania slave.','Najlepsze narzędzie do oceny ramek LIN to:',['Oscyloskop','Suwmiarka','Tester płynu chłodniczego'],0,'Oscyloskop pokazuje przebieg w czasie i pozwala odróżnić linię aktywną od zablokowanej.'),
L('c4','Komunikacja','Oscyloskop w diagnostyce auta','Zaawansowany','30 min','Bezpiecznie oglądać sygnały czujników i sterowania.','Oscyloskop pokazuje przebieg, którego multimetr uśrednia. Kluczowe są poprawna masa sondy, zakres napięcia, podstawa czasu i sposób wyzwalania.', ['Sprawdź dopuszczalne napięcie wejścia i rodzaj sondy.','Połącz masę z bezpiecznym punktem odniesienia badanego obwodu.','Zacznij od większego zakresu i wolniejszej podstawy czasu.','Ustaw trigger i porównaj amplitudę, częstotliwość oraz kształt.'], 'Do obwodów zapłonowych, sieciowych i wysokonapięciowych potrzebne są odpowiednie sondy i separacja.', 'Klips masy w przypadkowym punkcie; pomiar wtryskiwacza bez ochrony; wnioskowanie tylko z amplitudy.','Co multimetr zwykle ukrywa w sygnale PWM?',['Zmiany w czasie i wypełnienie','Kolor przewodu','Numer części'],0,'Multimetr podaje wartość uśrednioną, a oscyloskop pokazuje przebieg i wypełnienie.'),
L('m1','Silnik','Silnik kręci, ale nie odpala','Średni','30 min','Ułożyć diagnozę według warunków potrzebnych do startu.','Silnik potrzebuje właściwej prędkości rozruchu, synchronizacji, paliwa, powietrza, kompresji i sterowania. Nie zaczynaj od losowej części.', ['Sprawdź napięcie i RPM podczas rozruchu.','Oceń synchronizację wału i wałka oraz status immobilizera.','Sprawdź ciśnienie paliwa i sterowanie wtryskiem.','Potwierdź zapłon lub warunki samozapłonu i kompresję.'], 'Freeze frame i live data podczas kręcenia są ważniejsze niż dane na samym zapłonie.', 'Psikanie łatwopalnym środkiem bez planu; wymiana czujnika wyłącznie po DTC; brak kontroli rozrządu.','Brak RPM w live data podczas kręcenia kieruje najpierw do:',['Sygnału czujnika wału, wiązki i zasilania','Klimatyzacji','Czujnika parkowania'],0,'ECU potrzebuje sygnału położenia wału do rozpoznania obrotów i sterowania.'),
L('m2','Silnik','Czujniki 5 V: MAP, ciśnienie, położenie','Średni','25 min','Sprawdzić wspólną linię referencyjną bez wymiany wielu czujników.','Wiele czujników korzysta z wspólnego 5 V. Zwarcie jednego czujnika lub przewodu może obniżyć referencję i wygenerować wiele kodów.', ['Sprawdź 5 V, masę czujnika i sygnał.','Jeśli 5 V jest zaniżone, ustal wszystkie czujniki na tej gałęzi.','Odłączaj je kolejno zgodnie ze schematem, obserwując powrót 5 V.','Sprawdź wiązkę przed podejrzeniem sterownika.'], 'Sygnał musi mieścić się w zakresie i logicznie reagować na zmianę badanego parametru.', 'Podawanie 12 V na linię 5 V; zwieranie sygnału do masy; wymiana wszystkich czujników po kilku DTC.','Kilka czujników zgłasza zbyt niski sygnał jednocześnie. Najpierw sprawdź:',['Wspólne 5 V i masę czujników','Tylne lampy','Ciśnienie w oponach'],0,'Wspólne zasilanie referencyjne może powodować wiele pozornie niezależnych błędów.'),
L('m3','Silnik','MAF, MAP i wiarygodność powietrza','Średni','25 min','Ocenić dane czujników w kontekście, nie tylko zakresu.','Wartość może być elektrycznie poprawna, lecz niewiarygodna. Porównuj MAF, MAP, obroty, temperaturę, położenie przepustnicy i ciśnienie doładowania.', ['Sprawdź dolot pod kątem nieszczelności i filtra.','Porównaj MAP na zapłonie z ciśnieniem atmosferycznym.','Obserwuj MAF/MAP na biegu jałowym i pod obciążeniem.','Porównaj wartość zadaną i rzeczywistą oraz testuj EGR/turbo.'], 'Wykres podczas jazdy często ujawnia opóźnienie lub ograniczenie, którego nie widać na postoju.', 'Czyszczenie MAF agresywnym środkiem; diagnoza turbo na postoju; ignorowanie nieszczelności za MAF.','MAP na wyłączonym silniku powinien być zbliżony do:',['Ciśnienia atmosferycznego','0 bar absolutnego','Napięcia akumulatora'],0,'Przy braku pracy silnika kolektor jest połączony z atmosferą.'),
L('m4','Silnik','Układ paliwowy common rail','Zaawansowany','35 min','Bezpiecznie rozdzielić stronę niskiego i wysokiego ciśnienia.','Rozruch wymaga osiągnięcia minimalnego ciśnienia rail. Brak ciśnienia może wynikać z zasilania paliwem, przelewów, zaworu regulacji, pompy, czujnika lub prędkości rozruchu.', ['Sprawdź jakość paliwa, filtr i zasilanie niskiego ciśnienia.','Obserwuj ciśnienie zadane i rzeczywiste podczas rozruchu.','Wykonaj test przelewowy według procedury producenta.','Sprawdź sterowanie zaworem i wiarygodność czujnika przed skazaniem pompy.'], 'Układ wysokiego ciśnienia jest niebezpieczny. Nie luzuj przewodów podczas pracy i używaj procedur producenta.', 'Rozszczelnianie przewodu rail; wymiana pompy bez testu przelewów; ignorowanie prędkości rozruchu.','Co porównujesz podczas rozruchu diesla?',['Ciśnienie rail zadane i rzeczywiste','Tylko temperaturę zewnętrzną','Jasność świateł'],0,'Różnica pokazuje, czy układ osiąga warunek wymagany przez ECU do uruchomienia.'),
L('s1','Podwozie','ABS: czujnik prędkości koła','Średni','25 min','Odróżnić czujnik, pierścień, łożysko i wiązkę.','Kod czujnika koła nie oznacza automatycznie uszkodzonego czujnika. Sygnał zależy od typu aktywnego/pasywnego, zasilania, szczeliny i pierścienia magnetycznego.', ['Sprawdź DTC i live data wszystkich kół podczas wolnej jazdy.','Obejrzyj przewód, złącze, czujnik i łożysko/pierścień.','Ustal typ czujnika i właściwą metodę pomiaru.','Porównaj przebiegi lub wartości lewego i prawego koła.'], 'Zanik jednego sygnału przy tej samej prędkości pomaga ustalić stronę i warunki usterki.', 'Pomiar rezystancji aktywnego czujnika jak cewki; uszkodzenie pierścienia przy montażu łożyska; brak jazdy próbnej.','Kod czujnika ABS może spowodować także:',['Uszkodzony pierścień magnetyczny lub wiązka','Zużyty filtr kabinowy','Brak płynu do spryskiwaczy'],0,'Sterownik ocenia sygnał całego toru, nie tylko samego czujnika.'),
L('s2','Podwozie','Czujnik kąta skrętu i kalibracja','Średni','20 min','Rozpoznać usterkę mechaniczną, elektryczną i brak adaptacji.','Po naprawie geometrii, akumulatora lub kolumny może być potrzebna kalibracja. Najpierw sprawdź DTC, wartość przy kołach na wprost i komunikację.', ['Ustaw koła mechanicznie na wprost.','Odczytaj kąt skrętu i status kalibracji.','Sprawdź zasilanie, komunikację i poprawność montażu.','Wykonaj procedurę podstawową tylko po usunięciu usterek.'], 'Wartość powinna zmieniać się płynnie i logicznie w obie strony.', 'Kalibracja maskująca złą geometrię; kasowanie DTC bez jazdy testowej; wymiana czujnika bez zasilania/komunikacji.','Kiedy wykonujesz kalibrację?',['Po usunięciu usterek i prawidłowym ustawieniu mechanicznym','Zamiast naprawy wiązki','Zawsze przed odczytem DTC'],0,'Kalibracja nie naprawia problemu mechanicznego ani elektrycznego.'),
L('s3','Podwozie','EPB i elektryczny hamulec postojowy','Średni','25 min','Bezpiecznie serwisować zaciski i napęd EPB.','Tryb serwisowy cofa mechanizm zgodnie z procedurą. Wymuszenie tłoka lub podanie przypadkowego napięcia może uszkodzić przekładnię albo sterownik.', ['Odczytaj DTC i stan napięcia akumulatora.','Uruchom właściwy tryb serwisowy testerem lub procedurą producenta.','Sprawdź mechanikę zacisku, silnik, przewody i pobór prądu.','Po montażu wykonaj zamknięcie, adaptację i test działania.'], 'Różny pobór lewego i prawego silnika może wskazywać opór mechaniczny lub usterkę napędu.', 'Wciskanie tłoka bez trybu; praca przy słabym akumulatorze; brak adaptacji po wymianie.','Po wymianie klocków EPB należy:',['Wykonać procedurę zamknięcia/adaptacji i test','Tylko skasować radio','Odłączyć czujnik ABS'],0,'Sterownik musi prawidłowo ustalić pozycję mechanizmu po serwisie.'),
L('d1','Diagnostyka','OBD: autoscan, DTC i freeze frame','Podstawowy','25 min','Wykorzystać pełne dane przed kasowaniem błędów.','Autoscan pokazuje obraz całego auta. Status DTC i freeze frame pomagają odróżnić błąd obecny, sporadyczny i historyczny.', ['Zapewnij stabilne napięcie diagnostyczne.','Wykonaj pełny autoscan i zapisz raport.','Otwórz freeze frame i statusy ważnych DTC.','Skasuj błędy dopiero po zapisie i planie testu.'], 'Zwróć uwagę na wspólne napięcie, czas i przebieg wielu kodów — mogą mieć jedną przyczynę.', 'Kasowanie na początku; diagnoza tylko modułu silnika; ignorowanie kodów U i niskiego napięcia.','Po co jest freeze frame?',['Pokazuje warunki zapisania kodu','Programuje kluczyk','Mierzy grubość tarczy'],0,'Zapis warunków pozwala odtworzyć moment wystąpienia problemu.'),
L('d2','Diagnostyka','Live Data: wiarygodność i porównania','Średni','30 min','Odróżniać prawidłową liczbę od wiarygodnego sygnału.','Parametr może mieścić się w zakresie, lecz być nielogiczny względem innych danych. Porównuj czujniki przed startem, na biegu jałowym i pod obciążeniem.', ['Wybierz małą grupę powiązanych parametrów.','Sprawdź ich zgodność przed uruchomieniem.','Nagraj wykres podczas wystąpienia objawu.','Porównaj wartość zadaną, rzeczywistą i sterowanie.'], 'Zbyt wiele parametrów naraz obniża częstotliwość odświeżania i może ukryć szybkie zdarzenie.', 'Ocena pojedynczej chwili; brak jednostek; nagrywanie 50 PID jednocześnie; brak warunków testu.','Dlaczego wybieramy mało PID?',['Aby uzyskać szybsze próbkowanie i czytelny wykres','Aby skasować DTC','Aby zwiększyć napięcie'],0,'Tester ma ograniczoną szybkość transmisji; mniej PID daje częstsze próbki.'),
L('d3','Diagnostyka','Test elementów wykonawczych','Średni','25 min','Bezpiecznie wykorzystać aktywacje testera.','Test aktywacyjny sprawdza polecenie sterownika i reakcję obwodu, ale nie zawsze potwierdza pracę pod realnym obciążeniem.', ['Sprawdź warunki bezpieczeństwa i wymagania testu.','Obserwuj element, dźwięk, prąd lub zmianę parametru.','Jeśli brak reakcji, sprawdź zasilanie, sterowanie i obwód mocy.','Porównaj polecenie testera z rzeczywistą reakcją.'], 'Przy zaworze lub silniku obserwuj jednocześnie parametr potwierdzający jego efekt.', 'Aktywacja wentylatora przy dłoniach w pobliżu; wielokrotne sterowanie przegrzewające element; uznanie kliknięcia za pełną sprawność.','Kliknięcie przekaźnika potwierdza:',['Tylko ruch cewki/styku, nie jakość toru pod obciążeniem','Zawsze sprawny odbiornik','Brak zasilania'],0,'Styki mogą mieć duży opór, a odbiornik lub przewód nadal może być uszkodzony.'),
L('d4','Diagnostyka','Dymownica i nieszczelności','Średni','20 min','Znajdować nieszczelności dolotu i układów par paliwa.','Dym pod niskim, kontrolowanym ciśnieniem ujawnia nieszczelności, których nie widać. Układ musi być przygotowany zgodnie z jego konstrukcją.', ['Ustal testowany odcinek i bezpieczny punkt podania dymu.','Zaślep kontrolowane otwory zgodnie z procedurą.','Podaj dym przy bezpiecznym ciśnieniu.','Obserwuj przewody, kolektor, uszczelki i zawory.'], 'Po znalezieniu wycieku potwierdź naprawę ponownym testem i korektami paliwowymi.', 'Nadmierne ciśnienie; dym do gorącego układu; pomylenie normalnego odpowietrzenia z nieszczelnością.','Po naprawie nieszczelności należy:',['Powtórzyć test i sprawdzić dane','Od razu wymienić ECU','Zwiększyć bezpiecznik'],0,'Test końcowy potwierdza szczelność i wpływ naprawy na pracę silnika.'),
L('d5','Diagnostyka','Jazda próbna i potwierdzenie naprawy','Podstawowy','20 min','Zamknąć diagnozę dowodem, że objaw ustąpił.','Naprawa jest zakończona dopiero po odtworzeniu warunków, w których wcześniej występowała usterka, i sprawdzeniu braku skutków ubocznych.', ['Zdefiniuj przed naprawą warunki występowania objawu.','Po naprawie sprawdź DTC i wartości na postoju.','Wykonaj bezpieczną jazdę próbną w podobnych warunkach.','Zapisz wykres, status monitorów i końcowy autoscan.'], 'Nie wszystkie monitory gotowości wykonają się podczas krótkiej jazdy; poinformuj o tym klienta.', 'Krótki test bez obciążenia; kasowanie kodów tuż przed wydaniem; brak kontroli złączy ruszanych podczas naprawy.','Kiedy naprawę można uznać za potwierdzoną?',['Po samej wymianie części','Gdy objaw nie wraca w odtworzonych warunkach i wyniki są prawidłowe','Po skasowaniu kontrolki'],1,'Potrzebny jest test funkcjonalny, nie tylko brak lampki chwilę po skasowaniu.'),
L('a1','Zaawansowane','SRS i układy bezpieczeństwa','Zaawansowany','25 min','Rozumieć granice bezpiecznej diagnostyki SRS.','Poduszki i napinacze są elementami pirotechnicznymi. Wymagają procedur producenta, odłączenia zasilania i czasu rozładowania. Zwykłą próbówką nie testuje się zapalników.', ['Odczytaj DTC bez manipulowania złączami.','Sprawdź oficjalną procedurę odłączenia akumulatora i czas oczekiwania.','Używaj wyłącznie narzędzi i symulatorów przeznaczonych do SRS.','Po naprawie wykonaj kontrolę systemu zgodnie z dokumentacją.'], 'Nie mierz bezpośrednio rezystancji zapalnika zwykłym miernikiem, jeśli producent tego nie przewiduje.', 'Próbowanie poduszki napięciem; lutowanie przewodów bez procedury; praca bez zabezpieczenia przed ESD.','Czy zwykłą próbówką sprawdzamy obwód zapalnika?',['Tak','Nie','Tylko przy pracującym silniku'],1,'Przypadkowy prąd może uruchomić element pirotechniczny lub uszkodzić sterownik.'),
L('a2','Zaawansowane','Kodowanie, adaptacja i programowanie','Zaawansowany','30 min','Rozdzielić naprawę sprzętową od konfiguracji modułu.','Nowy lub używany moduł może wymagać kodowania, adaptacji, ochrony komponentu, przypisania VIN lub immobilizera. Programowanie wymaga stabilnego zasilania.', ['Zapisz pełny autoscan i konfigurację starego modułu.','Sprawdź zgodność numerów sprzętu i oprogramowania.','Podłącz stabilizowane podtrzymanie napięcia odpowiedniej mocy.','Po operacji wykonaj adaptacje, kalibracje i test wszystkich funkcji.'], 'Nie rozpoczynaj programowania przy słabym akumulatorze lub niestabilnym połączeniu sieciowym.', 'Wgranie pliku dla innego wariantu; brak kopii kodowania; odłączenie zasilania; uznanie braku funkcji za uszkodzenie hardware.','Najważniejszy warunek podczas programowania to:',['Stabilne zasilanie i właściwy plik/procedura','Włączone światła','Wyjęty filtr powietrza'],0,'Przerwanie zasilania lub błędny plik może unieruchomić moduł.'),
L('a3','Zaawansowane','Diagnostyka usterki okresowej','Zaawansowany','30 min','Uchwycić usterkę występującą tylko czasami.','Usterki okresowe wymagają rejestracji danych, testów poruszania wiązką, temperatury i odtwarzania warunków. Nie wolno prowokować uszkodzeń niebezpiecznie.', ['Zbierz dokładny wywiad: temperatura, wilgoć, czas jazdy i obciążenie.','Wybierz parametry oraz napięcia do długiego logowania.','Wykonaj kontrolowany wiggle test z obserwacją danych.','Porównaj moment objawu ze zmianą sygnału, zasilania lub komunikacji.'], 'Min/max multimetru, oscyloskop z rejestracją i logger OBD pomagają uchwycić krótkie zaniki.', 'Wymiana wielu części na próbę; grzanie elementów bez kontroli; poruszanie wiązką przy elementach wirujących.','Najlepsza strategia dla usterki okresowej to:',['Rejestrować dane w warunkach występowania objawu','Kasować błędy codziennie','Wymienić wszystkie czujniki'],0,'Korelacja objawu z zapisem pozwala wskazać konkretny tor lub warunek.'),
L('a4','Zaawansowane','Parazytujące napięcie i backfeed','Zaawansowany','25 min','Rozpoznawać napięcia pojawiające się przez inne odbiorniki.','Wysoka impedancja multimetru może pokazać napięcie bez zdolności dostarczenia prądu. Obciążenie testowe dobrane do obwodu ujawnia, czy zasilanie jest rzeczywiste.', ['Zmierz napięcie multimetrem.','Sprawdź schemat możliwych dróg zasilania zwrotnego.','Zastosuj bezpieczne obciążenie testowe właściwe dla obwodu.','Odłączaj podejrzane gałęzie i obserwuj zmianę.'], 'Nie używaj żarówki dużej mocy na liniach sygnałowych lub sterownikowych.', 'Uznanie każdego 12 V za mocne zasilanie; obciążanie delikatnej linii; pominięcie wspólnej masy.','Napięcie znika po małym obciążeniu. To może oznaczać:',['Zasilanie zwrotne lub duży opór źródła','Idealne zasilanie','Zawsze sprawny przewód'],0,'Źródło nie potrafi dostarczyć prądu, mimo że miernik bez obciążenia pokazuje napięcie.')
];

const paths=[
 {name:'Start od zera',icon:'🟢',desc:'Bezpieczne podstawy dla początkującego.',ids:['b1','b2','b3','b4','b5','b6']},
 {name:'Elektryka samochodowa',icon:'⚡',desc:'Zasilanie, rozruch, ładowanie, zwarcia i sterowniki.',ids:['e1','e2','e3','e4','e5','e6']},
 {name:'Diagnostyka komputerowa',icon:'💻',desc:'OBD, live data, aktywacje i komunikacja.',ids:['d1','d2','d3','c1','c2','c3','c4']},
 {name:'Silnik nie odpala',icon:'🧠',desc:'Systematyczna droga od rozruchu do paliwa i synchronizacji.',ids:['e1','e3','m1','m2','m4']},
 {name:'Poziom zaawansowany',icon:'🔴',desc:'SRS, programowanie, usterki okresowe i backfeed.',ids:['a1','a2','a3','a4']}
];
const cases=[
 {t:'Diesel kręci, ale nie odpala',d:'Akumulator 10,8 V podczas rozruchu, RPM 245, rail zadane 300 bar, rzeczywiste 70 bar.',q:'Najlepszy kolejny krok?',o:['Wymienić czujnik wału','Sprawdzić stronę niskiego ciśnienia i wykonać test przelewowy','Wymienić ECU'],a:1,w:'RPM jest obecne, ale rail nie osiąga warunku startu. Trzeba rozdzielić zasilanie paliwem, przelewy, regulację i pompę.'},
 {t:'Brak komunikacji z ABS',d:'Silnik i BCM komunikują się. W ABS zapisano brak komunikacji w innych modułach. Bezpiecznik ABS jest dobry wizualnie.',q:'Co sprawdzasz najpierw?',o:['Zasilania po obu stronach bezpiecznika i masy ABS pod obciążeniem','Wymieniasz pompę ABS','Kasujesz wszystkie kody'],a:0,w:'Dobry wygląd bezpiecznika nie potwierdza napięcia. Jeden brakujący plus lub masa wyłączy komunikację modułu.'},
 {t:'Akumulator rozładowuje się przez noc',d:'Po zamknięciu auta miernik pokazuje 1,2 A przez pierwsze 3 minuty.',q:'Jaki jest następny krok?',o:['Wyjmować bezpieczniki od razu','Poczekać na uśpienie modułów, obserwując prąd','Wymienić alternator'],a:1,w:'Początkowy pobór może być normalny. Najpierw trzeba znać czas uśpienia i wynik po stabilizacji.'},
 {t:'P0335 i brak RPM przy rozruchu',d:'Napięcie podczas rozruchu 10,6 V. Live data pokazuje 0 RPM.',q:'Co ma największą wartość diagnostyczną?',o:['Pomiar zasilania i przebiegu czujnika wału oraz wiązki','Wymiana świec','Czyszczenie EGR'],a:0,w:'Brak rozpoznania obrotów bezpośrednio kieruje do toru CKP, ale trzeba sprawdzić cały obwód.'},
 {t:'Jedno koło ABS pokazuje 0 km/h',d:'Pozostałe koła pokazują 12 km/h. Nowy czujnik nie zmienił objawu.',q:'Co dalej?',o:['Drugi nowy czujnik','Sprawdzenie wiązki, zasilania i pierścienia/łożyska','Wymiana ECU silnika'],a:1,w:'Nowa część nie wyklucza przerwy przewodu ani uszkodzonego pierścienia magnetycznego.'},
 {t:'Kilka kodów niskiego sygnału czujników',d:'MAP, czujnik ciśnienia klimatyzacji i pedał zgłaszają zbyt niskie napięcie.',q:'Wspólny trop?',o:['Linia referencyjna 5 V i masa czujników','Klocki hamulcowe','Antena radia'],a:0,w:'Kilka pozornie niezależnych czujników może korzystać z tej samej referencji 5 V.'},
 {t:'Rozrusznik kręci bardzo wolno',d:'Akumulator w teście obciążeniowym dobry. Spadek plusa 0,18 V, spadek masy 1,7 V.',q:'Gdzie szukać?',o:['Po stronie masowej silnika/rozrusznika','W czujniku MAF','W układzie wydechowym'],a:0,w:'1,7 V po stronie masy wskazuje duży opór przewodu, połączenia lub styku masowego.'},
 {t:'CAN około 120 Ω',d:'Zapłon wyłączony, sieć uśpiona. Między CAN-H i CAN-L jest około 120 Ω zamiast oczekiwanych 60 Ω.',q:'Co może to oznaczać?',o:['Brak jednej terminacji lub przerwę w części magistrali','Zawsze zwarcie do masy','Prawidłowy poziom oleju'],a:0,w:'Jedna dostępna terminacja 120 Ω daje taki wynik. Trzeba przeanalizować topologię konkretnej sieci.'}
];
const checklist=['Potwierdziłem objaw i warunki występowania','Zapisałem pełny autoscan, DTC i freeze frame','Sprawdziłem stan akumulatora oraz napięcie podczas rozruchu','Wykonałem oględziny złączy, wiązek, mas i śladów napraw','Mam właściwy schemat i pinout dla wariantu auta','Przed pomiarem znam oczekiwany wynik','Sprawdziłem zasilania i masy pod obciążeniem','Porównałem powiązane parametry live data','Każdy wniosek opieram na wyniku testu','Po naprawie odtworzyłem warunki usterki','Wykonałem końcowy autoscan i jazdę próbną','Zapisałem wyniki oraz wykonane czynności'];

let tab='lessons',currentCase=0;
function getDone(){try{return JSON.parse(localStorage.getItem('autodiagAcademyDone')||'[]')}catch(e){return[]}}
function setDone(x){try{localStorage.setItem('autodiagAcademyDone',JSON.stringify(x))}catch(e){}updateProgress()}
function updateProgress(){const d=getDone(),p=Math.round(d.length/lessons.length*100);$('academyDoneCount').textContent=d.length+' / '+lessons.length;$('academyProgressText').textContent=p+'% programu • '+(lessons.length-d.length)+' lekcji pozostało';$('academyProgressBar').style.width=p+'%'}
function tabs(){document.querySelectorAll('[data-academy-tab]').forEach(b=>b.classList.toggle('active',b.dataset.academyTab===tab))}
function showLessons(){
 const cats=['Wszystkie',...new Set(lessons.map(x=>x.cat))];
 $('academyContent').innerHTML='<div class="card"><div class="toolbar"><input id="academySearch" placeholder="Szukaj: CAN, miernik, rozrusznik, ABS..."><select id="academyCat">'+cats.map(x=>'<option>'+esc(x)+'</option>').join('')+'</select></div><div id="academyCount" class="muted small"></div></div><div id="academyLessonList" class="academyGrid"></div><div id="academyLessonDetail"></div>';
 const render=()=>{const q=$('academySearch').value.trim().toLowerCase(),c=$('academyCat').value,d=getDone();const rows=lessons.filter(x=>(c==='Wszystkie'||x.cat===c)&&(!q||JSON.stringify(x).toLowerCase().includes(q)));$('academyCount').textContent=rows.length+' lekcji';$('academyLessonList').innerHTML=rows.map(x=>'<article class="card academyCard" data-academy-id="'+x.id+'"><span class="academyDone">'+(d.includes(x.id)?'✅':'⬜')+'</span><span class="badge">'+esc(x.cat)+'</span><h2 style="margin-top:9px">'+esc(x.title)+'</h2><div class="academyMeta"><span class="badge">'+esc(x.level)+'</span><span class="badge">⏱ '+esc(x.time)+'</span></div><p class="muted small">'+esc(x.goal)+'</p></article>').join('');document.querySelectorAll('[data-academy-id]').forEach(b=>b.onclick=()=>openLesson(b.dataset.academyId));};
 $('academySearch').oninput=render;$('academyCat').onchange=render;render();
}
function openLesson(id){
 const x=lessons.find(v=>v.id===id);if(!x)return;$('academyLessonList').style.display='none';
 $('academyLessonDetail').innerHTML='<div class="card"><button class="secondary" id="academyBack">← Wróć do lekcji</button><div class="academyMeta"><span class="badge">'+esc(x.cat)+'</span><span class="badge">'+esc(x.level)+'</span><span class="badge">⏱ '+esc(x.time)+'</span></div><h1>'+esc(x.title)+'</h1><div class="okbox"><b>Cel lekcji</b><br>'+esc(x.goal)+'</div><h2 style="margin-top:18px">Jak to działa?</h2><p>'+esc(x.theory)+'</p><h2>Procedura krok po kroku</h2>'+x.steps.map((s,i)=>'<div class="academyStep"><div class="academyStepNum">'+(i+1)+'</div><div class="step" style="margin:0">'+esc(s)+'</div></div>').join('')+'<div class="grid"><div class="result"><b>📏 Pomiary i interpretacja</b><br>'+esc(x.measure)+'</div><div class="alert"><b>⚠️ Typowe błędy</b><br>'+esc(x.mistakes)+'</div></div><div class="card"><h2>Test wiedzy</h2><p><b>'+esc(x.q)+'</b></p><div id="academyQuizOpts">'+x.opts.map((o,i)=>'<button class="academyQuiz" data-academy-answer="'+i+'">'+String.fromCharCode(65+i)+'. '+esc(o)+'</button>').join('')+'</div><div id="academyQuizResult"></div></div><button class="good" id="academyComplete">✓ Oznacz lekcję jako ukończoną</button></div>';
 $('academyBack').onclick=showLessons;document.querySelectorAll('[data-academy-answer]').forEach(b=>b.onclick=()=>{const n=+b.dataset.academyAnswer;document.querySelectorAll('[data-academy-answer]').forEach((z,i)=>{z.disabled=true;z.classList.toggle('correct',i===x.ans);z.classList.toggle('wrong',i===n&&n!==x.ans)});$('academyQuizResult').innerHTML='<div class="'+(n===x.ans?'okbox':'badbox')+'"><b>'+(n===x.ans?'Dobrze!':'Nie tym razem.')+'</b><br>'+esc(x.why)+'</div>'});
 $('academyComplete').onclick=()=>{const d=getDone();if(!d.includes(id))d.push(id);setDone(d);$('academyComplete').textContent='✅ Lekcja ukończona';$('academyComplete').disabled=true};$('academyLessonDetail').scrollIntoView({behavior:'smooth',block:'start'});
}
function showPaths(){$('academyContent').innerHTML='<div class="academyGrid">'+paths.map(p=>{const d=getDone(),done=p.ids.filter(x=>d.includes(x)).length;return '<div class="card"><div class="kpi">'+p.icon+'</div><h2>'+esc(p.name)+'</h2><p class="muted">'+esc(p.desc)+'</p><div class="academyProgress"><span style="width:'+Math.round(done/p.ids.length*100)+'%"></span></div><p class="small">'+done+' / '+p.ids.length+' ukończonych</p><div class="academyPath">'+p.ids.map(id=>{const x=lessons.find(l=>l.id===id);return '<span>'+(d.includes(id)?'✅ ':'')+esc(x.title)+'</span>'}).join('<b>→</b>')+'</div></div>'}).join('')+'</div>'}
function showCases(){currentCase=0;$('academyContent').innerHTML='<div id="academyCaseBox"></div>';renderCase()}
function renderCase(){const x=cases[currentCase];$('academyCaseBox').innerHTML='<div class="card"><span class="badge">Przypadek '+(currentCase+1)+' / '+cases.length+'</span><h2 style="margin-top:10px">'+esc(x.t)+'</h2><div class="result">'+esc(x.d)+'</div><p><b>'+esc(x.q)+'</b></p>'+x.o.map((o,i)=>'<button class="choice academyCaseBtn" data-case-answer="'+i+'">'+String.fromCharCode(65+i)+'. '+esc(o)+'</button>').join('')+'<div id="academyCaseResult"></div></div>';document.querySelectorAll('[data-case-answer]').forEach(b=>b.onclick=()=>{const n=+b.dataset.caseAnswer;document.querySelectorAll('[data-case-answer]').forEach(z=>z.disabled=true);$('academyCaseResult').innerHTML='<div class="'+(n===x.a?'okbox':'badbox')+'"><b>'+(n===x.a?'Prawidłowy tok diagnozy.':'Ten krok nie zawęża najlepiej usterki.')+'</b><br>'+esc(x.w)+'</div><button class="primary" id="academyNextCase" style="margin-top:12px">'+(currentCase+1<cases.length?'Następny przypadek →':'Zacznij od początku')+'</button>';$('academyNextCase').onclick=()=>{currentCase=(currentCase+1)%cases.length;renderCase()}})}
function showChecklist(){$('academyContent').innerHTML='<div class="card"><h2>Uniwersalna checklista diagnosty</h2><p class="muted">Zaznaczenia działają w tej sesji. Lista pomaga utrzymać logiczną kolejność pracy.</p>'+checklist.map(x=>'<label class="step" style="display:flex;gap:10px;align-items:flex-start"><input type="checkbox" style="width:auto;margin-top:3px"> <span>'+esc(x)+'</span></label>').join('')+'</div><div class="note"><b>Zasada końcowa:</b> nie wymieniaj elementu, dopóki nie potwierdzisz jego zasilania, masy, sterowania oraz reakcji obwodu. Po naprawie zawsze wykonaj test potwierdzający.</div>'}
function render(){tabs();if(tab==='lessons')showLessons();if(tab==='paths')showPaths();if(tab==='cases')showCases();if(tab==='checklist')showChecklist()}
document.querySelectorAll('[data-academy-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.academyTab;render()});
$('academyReset').onclick=()=>{if(confirm('Wyzerować postęp wszystkich lekcji Akademii?')){setDone([]);render()}};
updateProgress();render();
})();
