(function(){
'use strict';
const f=(cat,title,sym,causes,checks,repair,tip)=>({cat,title,sym,causes,checks,repair,tip});
window.EXTRA_ELECTRICAL_FAULTS=[
f('Akumulator i pobór prądu','Akumulator sprawny, ale auto po kilku dniach nie odpala','Stopniowe rozładowanie podczas postoju bez oczywistego odbiornika',['moduł okresowo się wybudza','keyless wykrywa klucz w pobliżu','alarm, radio lub lokalizator','dioda alternatora ma upływ'],['naładuj i przetestuj pojemność akumulatora','zmierz pobór dopiero po pełnym uśpieniu auta','rejestruj pobór przez kilka godzin','lokalizuj obwód pomiarem spadku napięcia na bezpiecznikach','sprawdź alternator i wyposażenie dodatkowe'],'Usuń odbiornik lub przyczynę wybudzania; potwierdź stabilny pobór spoczynkowy.','Krótki skok poboru może być normalny — ważny jest czas i częstotliwość wybudzeń.'),
f('Akumulator i pobór prądu','Klemy grzeją się podczas rozruchu','Rozrusznik kręci wolno, klema lub przewód robi się gorący',['luźne lub utlenione połączenie','pęknięta żyła przewodu','zbyt mały przekrój przewodu','nadmierny prąd rozrusznika'],['zmierz spadek napięcia na każdej klemie i przewodzie podczas rozruchu','porównaj temperaturę połączeń','zmierz prąd rozrusznika','sprawdź zaciskanie końcówek'],'Oczyść i prawidłowo zaciśnij połączenia albo wymień przewód; sprawdź rozrusznik przy nadmiernym prądzie.','Gorące miejsce zwykle wskazuje punkt największej rezystancji.'),
f('Oświetlenie','Światło STOP nie działa w klapie','Trzecie światło STOP nie świeci lub działa przy poruszaniu klapą',['pęknięte przewody w przelotce','korozja złącza lampy','uszkodzona listwa LED','brak wyjścia BCM'],['sprawdź DTC modułu nadwozia','zmierz zasilanie i masę przy lampie podczas hamowania','poruszaj wiązką w przelotce','sprawdź ciągłość przewodów pod obciążeniem'],'Napraw elastycznie wiązkę lub wymień lampę po potwierdzeniu zasilania.','W klapie przewód często jest pęknięty pod nieuszkodzoną izolacją.'),
f('Oświetlenie','Kierunkowskaz miga szybko lub nie działa z jednej strony','Szybkie miganie, błąd żarówki albo brak jednego kierunku',['spalona żarówka lub LED','słaba masa lampy','nadpalona oprawka','przerwa przewodu','niewłaściwe LED bez obciążenia'],['sprawdź wszystkie lampy po tej stronie','zmierz spadek masy pod obciążeniem','obejrzyj oprawki i złącza','sprawdź sterowanie PWM z BCM'],'Napraw masę, oprawkę lub wiązkę; zastosuj właściwy typ lampy i kodowanie.','Napięcie bez żarówki może wyglądać prawidłowo mimo słabego styku.'),
f('Wycieraczki','Wycieraczki uruchamiają się samoczynnie','Pracują bez polecenia, losowo lub po włączeniu zapłonu',['wilgoć w BSM/BCM','uszkodzona manetka','zwarcie przewodów sterujących','uszkodzony czujnik deszczu','brak komunikacji z modułem kolumny'],['odczytaj stan manetki i czujnika w Live Data','wykonaj pełny skan DTC','sprawdź wilgoć oraz złącza BSM/BCM','sprawdź zasilania i magistralę LIN/CAN','odłączaj wejścia zgodnie ze schematem'],'Usuń wilgoć lub zwarcie; napraw element wskazany przez błędne polecenie.','Tryb awaryjny modułu może celowo uruchamiać wycieraczki po utracie komunikacji.'),
f('Wycieraczki','Wycieraczki nie wracają do pozycji spoczynkowej','Zatrzymują się na szybie lub wykonują dodatkowe cykle',['uszkodzony styk parkowania w silniku','przestawiony mechanizm','błąd modułu sterującego','zatarte cięgna'],['sprawdź sygnał pozycji parkowania','wykonaj test elementów wykonawczych','skontroluj ustawienie mechanizmu i pobór prądu','sprawdź przewody silnika'],'Napraw silnik/styk parkowania albo ustaw mechanizm zgodnie z pozycją bazową.','Nie przestawiaj ramion na wieloklinie przed sprawdzeniem pozycji mechanizmu.'),
f('Centralny zamek','Tylna klapa nie otwiera się mimo pracy siłownika','Słychać napęd, ale zamek nie zwalnia',['zapieczony mechanizm zamka','pęknięte cięgno','zła regulacja zaczepu','spadek napięcia','uszkodzony mikrostyk'],['obserwuj status klapy i polecenie w Live Data','zmierz napięcie na siłowniku podczas pracy','sprawdź ręcznie mechanizm po awaryjnym otwarciu','skontroluj wiązkę przelotki'],'Oczyść i wyreguluj mechanizm albo wymień uszkodzony zamek/cięgno.','Dźwięk siłownika nie potwierdza pełnego skoku mechanizmu.'),
f('Audio i multimedia','Radio działa, ale brak dźwięku we wszystkich głośnikach','Jednostka włącza się, ekran działa, brak audio',['brak zasilania wzmacniacza','przerwa światłowodu MOST','wzmacniacz zalany lub uszkodzony','brak sygnału wake-up','aktywne wyciszenie MUTE'],['wykonaj skan modułów multimedialnych','sprawdź zasilania i masy wzmacniacza','sprawdź pętlę MOST','sprawdź sygnał włączenia i status MUTE'],'Napraw zasilanie/pętlę komunikacji albo wzmacniacz po zlokalizowaniu przerwy.','W pętli MOST awaria jednego urządzenia może zatrzymać cały system.'),
f('Audio i multimedia','Wzmacniacz charczy tylko na zimno','Zniekształcenia po uruchomieniu znikają po nagrzaniu',['wyschnięte kondensatory','zimne luty','uszkodzony stopień zasilacza','zawilgocenie złącza','głośnik z uszkodzoną cewką'],['zamień kanały lub głośniki, aby ustalić źródło','sprawdź zasilanie pod obciążeniem i tętnienia','użyj kontrolowanego chłodzenia małych stref','sprawdź kondensatory ESR po demontażu'],'Napraw zasilacz lub połączenia; głośnik wymień tylko jeśli usterka podąża za nim.','Objaw zależny od temperatury lokalizuj małymi strefami.'),
f('Dmuchawa i HVAC','Nawiew działa tylko na najwyższym biegu','Niższe biegi dmuchawy nie działają',['bezpiecznik termiczny rezystora','uszkodzony rezystor biegów','przegrzane złącze','silnik dmuchawy pobiera za duży prąd'],['zmierz prąd silnika dmuchawy','sprawdź rezystor/regulator i złącze','sprawdź filtr kabinowy i lekkość obrotu','zweryfikuj sterowanie panelu HVAC'],'Wymień rezystor/regulator i usuń przyczynę przegrzania.','Bez kontroli poboru silnika nowy regulator może szybko ulec awarii.'),
f('Dmuchawa i HVAC','Dmuchawa pracuje po wyłączeniu zapłonu','Wentylator kabiny nie wyłącza się i rozładowuje akumulator',['zwarty regulator PWM','sklejony przekaźnik','błędne sterowanie panelu HVAC','wilgoć w module'],['odłącz sterowanie regulatora i obserwuj pracę','sprawdź napięcie wyjściowe regulatora','odczytaj żądanie dmuchawy w Live Data','sprawdź przekaźnik'],'Wymień zwarty regulator lub napraw sterowanie/przekaźnik.','Zwarcie tranzystora regulatora często powoduje maksymalną pracę bez polecenia.'),
f('Wentylatory chłodnicy','Wentylator chłodnicy nie uruchamia się','Temperatura rośnie na postoju, klimatyzacja słabo chłodzi',['bezpiecznik dużej mocy','moduł wentylatora','silnik wentylatora','czujnik ECT lub ciśnienia A/C','brak polecenia ECU'],['wykonaj aktywację testerem','sprawdź zasilanie, masę i sterowanie przy module','zmierz prąd silnika','porównaj ECT i ciśnienie A/C z wartościami logicznymi'],'Napraw zasilanie, moduł lub wentylator; czujnik wymień po potwierdzeniu błędnego odczytu.','Nie podawaj zasilania na nieznane piny modułu PWM/LIN.'),
f('Przyczepa','Po podłączeniu przyczepy błędy świateł','Lampy przyczepy działają losowo albo auto zgłasza awarie',['korozja gniazda 7/13 pin','zła masa przyczepy','brak dedykowanego modułu haka','przeciążenie wyjść BCM','błędne kodowanie'],['sprawdź gniazdo i masę pod obciążeniem','zmierz pobór lamp przyczepy','zeskanuj moduł haka i BCM','sprawdź kodowanie i CAN'],'Napraw gniazdo/masę, zastosuj właściwy moduł i wykonaj kodowanie.','Nie zasilaj wielu lamp bezpośrednio z BCM, jeśli wymagany jest moduł haka.'),
f('Fotele i ogrzewanie','Podgrzewanie fotela wyłącza się po chwili','Kontrolka gaśnie lub grzanie działa nierówno',['przerwa maty grzewczej','czujnik temperatury NTC','złącze pod fotelem','moduł fotela','zbyt duży prąd'],['odczytaj DTC i temperaturę maty','zmierz ciągłość według schematu','poruszaj fotelem i obserwuj instalację','sprawdź zasilanie pod obciążeniem'],'Napraw matę, czujnik albo złącze; zabezpiecz wiązkę przed naprężeniem.','Pod fotelem często biegną też obwody SRS — zachowaj procedurę bezpieczeństwa.'),
f('Czujniki parkowania','PDC emituje długi ton po włączeniu','System wyłącza się natychmiast po aktywacji',['uszkodzony lub zabrudzony czujnik','woda w złączu','przerwa wiązki zderzaka','brak zasilania modułu'],['odczytaj DTC PDC','porównaj odległości czujników','sprawdź zasilanie i sygnał','zamień czujniki miejscami, jeśli są zgodne'],'Napraw wiązkę lub wymień czujnik wskazany testem porównawczym.','Odsłuch tykania jest tylko testem wstępnym.'),
f('Szyby elektryczne','Szyba cofa się podczas zamykania','Funkcja AUTO podnosi szybę i natychmiast ją opuszcza',['utracona adaptacja','duży opór prowadnic','krzywo ustawiona szyba','uszkodzony mechanizm lub czujnik siły'],['wykonaj inicjalizację','sprawdź lekkość ruchu i prowadnice','obserwuj prąd silnika','sprawdź mocowanie szyby'],'Usuń opór lub napraw mechanizm, następnie wykonaj adaptację.','Nie wyłączaj ochrony przeciwzgnieceniowej przed usunięciem przyczyny.'),
f('Kamera i ADAS','Błąd kamery po wymianie szyby','Lane Assist lub rozpoznawanie znaków nie działa',['kamera przesunięta','niewłaściwy uchwyt szyby','brak kalibracji','błąd geometrii','zabrudzone pole widzenia'],['sprawdź DTC i status kalibracji','zweryfikuj numer i uchwyt szyby','sprawdź geometrię i opony','wykonaj kalibrację zgodnie z producentem'],'Zamontuj właściwe elementy i przeprowadź wymaganą kalibrację ADAS.','Kasowanie błędu nie zastępuje kalibracji.'),
f('Immobilizer i kluczyk','Pilot działa, ale silnik odpala i gaśnie','Silnik startuje na sekundę, miga kontrolka immobilizera',['transponder nie jest rozpoznany','uszkodzona antena przy stacyjce','klucz utracił adaptację','brak komunikacji BCM–ECU','spadek napięcia podczas rozruchu'],['spróbuj klucza zapasowego','odczytaj status autoryzacji i DTC','sprawdź antenę i wiązkę','sprawdź napięcie rozruchu oraz CAN'],'Napraw antenę/komunikację albo zaprogramuj właściwy klucz.','Bateria pilota i transponder immobilizera to dwa różne układy.')
];

window.EXTRA_MODULE_FAULTS=[
f('Układ paliwowy','Diesel kręci, ale ciśnienie rail jest za niskie','Ciśnienie nie osiąga progu uruchomienia',['zapowietrzenie lub filtr','pompa wstępna','nadmierne przelewy wtryskiwaczy','IMV/SCV','pompa wysokiego ciśnienia','czujnik rail'],['porównaj ciśnienie wymagane i rzeczywiste','sprawdź niski obwód i obecność powietrza','wykonaj test przelewowy','sprawdź IMV/SCV i czujnik','skontroluj filtr pod kątem opiłków'],'Usuń przyczynę niedoboru paliwa; przy opiłkach oczyść cały układ.','Nie luzuj przewodów Common Rail na pracującym silniku.'),
f('Układ paliwowy','Silnik gaśnie po rozgrzaniu','Po ostygnięciu ponownie się uruchamia',['CKP/CMP traci sygnał','pompa traci wydajność','przekaźnik lub zasilanie ECU','zawór ciśnienia','usterka termiczna sterownika'],['rejestruj RPM, ciśnienie paliwa i napięcie ECU w chwili zgaśnięcia','sprawdź CKP/CMP oscyloskopem na gorąco','zmierz prąd pompy i spadki','odczytaj DTC bez kasowania'],'Napraw obwód, którego parametr zanika dokładnie w chwili usterki.','Pomiary bezpośrednio po zgaśnięciu są najcenniejsze.'),
f('Dolot i turbo','Turbo przeładowuje – P0234','Tryb awaryjny przy mocnym przyspieszeniu',['zapieczona geometria VNT','zawór lub przewody podciśnienia','zablokowany wastegate','błędny MAP','aktuator'],['porównaj boost zadany i rzeczywisty','sprawdź pełny skok aktuatora','sprawdź elektrozawór i przewody','zweryfikuj MAP przy KOEO'],'Napraw sterowanie lub mechanizm turbiny i potwierdź wynik w logu drogowym.','Przeładowanie może wynikać z zacinającej się geometrii.'),
f('Dolot i turbo','Olej w przewodach intercoolera','W dolocie znajduje się dużo oleju, auto może dymić',['mgła olejowa z odmy','nadmierne przedmuchy','uszkodzone turbo','niedrożny odpływ oleju','za wysoki poziom oleju'],['oceń ilość oleju','sprawdź turbo','sprawdź odmę i ciśnienie skrzyni korbowej','skontroluj odpływ oraz poziom'],'Usuń przyczynę i oczyść dolot/intercooler przed uruchomieniem po dużym wycieku.','Duża ilość oleju w dieslu grozi rozbiegnięciem silnika.'),
f('DPF / SCR','DPF regeneruje się zbyt często','Krótkie odstępy między regeneracjami',['duża produkcja sadzy','niedogrzany silnik','błędny czujnik różnicy ciśnień','duża masa popiołu','nieszczelność dolotu'],['sprawdź dystans, sadzę i popiół','porównaj różnicę ciśnień przy kilku obrotach','sprawdź EGT i ECT','oceń wtryski, MAF i EGR','sprawdź przerwane regeneracje'],'Usuń przyczynę tworzenia sadzy lub błędnego pomiaru; oceń stan filtra.','Wymuszona regeneracja bez naprawy przyczyny daje krótki efekt.'),
f('DPF / SCR','AdBlue odlicza rozruch mimo pełnego zbiornika','Komunikat o blokadzie uruchomienia za określony dystans',['zła jakość płynu','skrystalizowany wtryskiwacz','pompa lub grzałka','czujnik NOx','brak adaptacji'],['odczytaj DTC SCR i NOx','sprawdź ciśnienie oraz test dozowania','sprawdź temperatury i grzałki','oceń jakość płynu','wykonaj procedurę potwierdzenia naprawy'],'Napraw układ SCR i wykonaj wymagany cykl/adaptację.','Samo dolanie płynu nie skasuje odliczania przy aktywnej usterce.'),
f('Chłodzenie','Silnik przegrzewa się tylko na postoju','W trasie temperatura prawidłowa, na postoju rośnie',['wentylator nie działa','brak sterowania','zabrudzona chłodnica/skraplacz','niski poziom płynu','pompa o małej wydajności'],['sprawdź aktywację wentylatora i biegi','sprawdź temperaturę wejścia/wyjścia chłodnicy','skontroluj przepływ powietrza','sprawdź ciśnienie i odpowietrzenie'],'Napraw wentylator/sterowanie lub przywróć przepływ.','Nie otwieraj gorącego układu chłodzenia.'),
f('Chłodzenie','Silnik nie osiąga temperatury roboczej','Temperatura spada w trasie, ogrzewanie jest słabe',['termostat otwarty','błędny ECT','wentylator pracuje stale','zły termostat po wymianie'],['porównaj ECT z temperaturą obudowy','obserwuj nagrzewanie przewodów od zimnego startu','sprawdź polecenie wentylatora','porównaj ECT i IAT po postoju'],'Wymień termostat/czujnik lub napraw sterowanie wentylatorem.','Zbyt zimny silnik może blokować regenerację DPF.'),
f('Smarowanie','Kontrolka ciśnienia oleju zapala się na ciepło','Na wolnych obrotach po rozgrzaniu pojawia się ostrzeżenie',['niski poziom lub zły olej','pompa oleju','zanieczyszczony smok','zużyte panewki','czujnik lub instalacja'],['sprawdź poziom oleju','zmierz ciśnienie manometrem na zimno i ciepło','sprawdź obroty jałowe','dopiero potem diagnozuj czujnik'],'Przy niskim ciśnieniu nie eksploatuj silnika; usuń przyczynę mechaniczną.','Kontrolki ciśnienia oleju nie traktuj jak przypomnienia serwisowego.'),
f('Mechanika silnika','Niska kompresja na jednym cylindrze','Wypadanie nie podąża za cewką ani wtryskiem',['nieszczelny zawór','pierścienie','uszczelka głowicy','tłok','problem rozrządu'],['wykonaj próbę kompresji','wykonaj próbę szczelności cylindra','sprawdź kierunek ucieczki','użyj endoskopu i sprawdź rozrząd'],'Napraw mechanikę według miejsca ucieczki wskazanego testem.','Porównanie cylindrów jest ważniejsze niż jedna wartość uniwersalna.'),
f('Zapłon','Wypadanie zapłonu tylko pod obciążeniem','Na biegu jałowym poprawnie, podczas przyspieszania szarpie',['duża przerwa świecy','cewka przebija pod ciśnieniem','niskie ciśnienie paliwa','uboga mieszanka','niska kompresja'],['sprawdź licznik misfire podczas jazdy','porównaj świece','zamień cewki','sprawdź ciśnienie i korekty pod obciążeniem','sprawdź zapłon oscyloskopem'],'Wymień element, jeśli usterka za nim podąża; inaczej diagnozuj paliwo i mechanikę.','Iskra na wykręconej świecy nie potwierdza pracy pod ciśnieniem.'),
f('Rozrząd / VVT','Błąd korelacji P0016/P0017','Trudny rozruch, brak mocy lub nierówna praca',['rozciągnięty łańcuch lub pasek','koło VVT','niskie ciśnienie oleju','zawór VVT','koło impulsowe lub czujnik'],['sprawdź CKP/CMP oscyloskopem','zweryfikuj mechaniczne ustawienie','sprawdź olej i ciśnienie','testuj VVT i pozycję zadaną/rzeczywistą'],'Napraw rozrząd/VVT; czujnik wymień po potwierdzeniu sygnału.','Kasowanie adaptacji nie naprawi przestawionego rozrządu.'),
f('Skrzynia automatyczna','Skrzynia szarpie po rozgrzaniu','Zmiany biegów pogarszają się z temperaturą',['poziom lub stan ATF','zużyte sprzęgła','mechatronika','adaptacje na granicy','chłodzenie skrzyni'],['odczytaj DTC i temperaturę ATF','sprawdź poziom według procedury','porównaj obroty i poślizg','sprawdź ciśnienia/adaptacje','oceń chłodnicę ATF'],'Napraw wyciek, mechatronikę lub mechanikę według pomiarów.','Procedura poziomu oleju zależy od typu skrzyni.'),
f('Skrzynia DSG / DCT','Brak wstecznego lub wybranych biegów','Skrzynia działa tylko na części przełożeń',['sprzęgło lub widełka sekcji','mechatronika','czujnik położenia','niskie ciśnienie','uszkodzenie mechaniczne'],['odczytaj pełne DTC','sprawdź pozycje wybieraków i ciśnienie','wykonaj test elementów','sprawdź olej i opiłki','oceń adaptacje'],'Napraw odpowiednią sekcję lub mechatronikę po potwierdzeniu.','Nie powtarzaj adaptacji przy uszkodzeniu mechanicznym.'),
f('ABS / ESP','ABS uruchamia się przy małej prędkości bez poślizgu','Pedał pulsuje tuż przed zatrzymaniem',['pierścień impulsowy','pierścień magnetyczny łożyska','zła szczelina','korozja pod czujnikiem','zły rozmiar opony'],['zaloguj prędkości kół do zatrzymania','znajdź koło, którego odczyt spada wcześniej','sprawdź przebieg czujnika','obejrzyj pierścień i mocowanie'],'Napraw pierścień/łożysko, szczelinę lub czujnik wskazanego koła.','Brak DTC nie wyklucza krótkiego zaniku przy małej prędkości.'),
f('ABS / ESP','Kontrolki ABS i ESP po wymianie akumulatora','Po spadku napięcia świecą kontrolki',['utracona kalibracja kąta skrętu','kody niskiego napięcia','brak ustawień podstawowych','problem zasilania'],['sprawdź akumulator i ładowanie','wykonaj skan i zapisz DTC','sprawdź kąt kierownicy','wykonaj kalibrację','odbyj wymagany cykl jazdy'],'Usuń błędy napięcia i wykonaj ustawienia podstawowe.','Zapisz kody przed kasowaniem.'),
f('SRS / Airbag','Kontrolka poduszki po przesunięciu fotela','Błąd napinacza lub bocznej poduszki pojawia się okresowo',['luźne złącze pod fotelem','naciągnięta wiązka','korozja styków','mata zajęcia fotela'],['odczytaj dokładny DTC','odłącz akumulator i odczekaj wymagany czas','obejrzyj wiązkę bez próbówki','sprawdź parametry fotela bez manipulacji zapalnikiem'],'Napraw wiązkę metodą producenta albo wymień uszkodzony element.','Do zapalników SRS nie podłączaj omomierza ani zasilania.'),
f('Klimatyzacja','Sprężarka działa, ale klimatyzacja słabo chłodzi','Temperatura nawiewu wysoka mimo pracy układu',['zła ilość czynnika','słaby przepływ skraplacza','zawór rozprężny','sprężarka','klapa mieszania'],['zmierz oba ciśnienia i temperaturę otoczenia','sprawdź masę czynnika','sprawdź wentylatory i temperatury przewodów','sprawdź klapy HVAC','oceń sterowanie sprężarki'],'Napraw element wskazany przez zależność ciśnień i temperatur.','Ciśnienie statyczne nie potwierdza prawidłowej masy czynnika.'),
f('ECU / sterowniki','Sterownik nie uruchamia się po naprawie wiązki','Brak komunikacji mimo usunięcia zwarcia',['brak jednego z zasilań','brak masy pod obciążeniem','uszkodzony driver','brak wake-up','kodowanie lub immobilizer'],['sprawdź wszystkie zasilania na pinach','obciąż obwody zasilania','sprawdź pobór prądu i CAN','zweryfikuj wake-up i immobilizer','porównaj konfigurację'],'Napraw brakujący warunek; sterownik podejrzewaj po pełnym potwierdzeniu instalacji.','Ciągłość przewodu nie potwierdza pracy pod obciążeniem.')
];
})();
